server {
	listen 					8080 ssl;
	listen					[::]:8080 ssl;
	server name				ktintim.42.fr;

	# path to ssl certificate
	ssl_certificate 		path/to/cerificate.crt;
	ssl_certificate_key		path/to/key.key;
	ssl_protocols			TLSv1.2 TLSv1.3;	#specify TLS protoco
	
	root /var/www/html;

	index index.php index.html

	location / {
		try_files $uri $uri/ =404;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
	}
}