services: 
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443" # 443:???
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - nginx
      - mariaDB
    volumes:
      - wordpress:/var/www/html/wp-content
    networks:
      - inception

  mariaDB:
    container_name: mariaDB
    image: mariadb:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - DB:/DB/path
    networks:
      - inception

volumes:
  wordpress:

  DB:

networks:
  inception:
    driver: bridge